tap "aws/tap"
tap "dotzero/tap"
tap "homebrew/bundle"
tap "homebrew/services"
tap "remotemobprogramming/brew"
brew "webp"
brew "openssl@3"
brew "awscli"
brew "docker", link: false
brew "ffmpeg"
brew "gcc"
brew "go"
brew "graphviz"
brew "htop"
brew "httpd"
brew "k6"
brew "kcat"
brew "kubernetes-cli"
brew "mas"
brew "node"
brew "nvm"
brew "python@3.8"
brew "rust"
brew "the_silver_searcher"
brew "zplug"
brew "zsh"
cask "docker"
cask "flutter"
cask "iterm2"
cask "jetbrains-toolbox"
cask "keepingyouawake"
cask "lens"
cask "macs-fan-control"
cask "miro"
cask "notion"
cask "orion"
cask "postman"
cask "spectacle"
cask "telegram"
cask "visual-studio-code"
cask "whatsapp"
mas "AdBlock", id: 1402042596
mas "CopyClip", id: 595191960
mas "GarageBand", id: 682658836
mas "Grammarly for Safari", id: 1462114288
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LastPass", id: 926036361
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
vscode "bradlc.vscode-tailwindcss"
vscode "dart-code.dart-code"
vscode "dart-code.flutter"
vscode "dbaeumer.vscode-eslint"
vscode "dracula-theme.theme-dracula"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "file-icons.file-icons"
vscode "firsttris.vscode-jest-runner"
vscode "github.vscode-github-actions"
vscode "golang.go"
vscode "mobtime.mobtime"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.python"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vsliveshare.vsliveshare"
vscode "redhat.vscode-yaml"
vscode "svelte.svelte-vscode"
vscode "wakatime.vscode-wakatime"
vscode "wholroyd.jinja"
